#!/usr/bin/env bash

source cue_colors

function _ansi {
  echo -n "\[\e[${1}m\]"
}

function _iterm {
  echo -n -e "\033]P${1}\033\\"
}

sblue="$(_ansi "$_sblue")"
scyan="$(_ansi "$_scyan")"
sgreen="$(_ansi "$_sgreen")"
smagenta="$(_ansi "$_smagenta")"
sorange="$(_ansi "$_sorange")"
sred="$(_ansi "$_sred")"
sviolet="$(_ansi "$_sviolet")"
syellow="$(_ansi "$_syellow")"

function sdark {
  export CUE_SCHEME="sdark"
  case "${TERM_PROGRAM:-}" in
    iTerm.app)
      export sbg="$(_ansi "$_sbase03")"
      export sm="$(_ansi "$_sbase02")"
      export stext="$(_ansi "$_sbase0")"
      export scomment="$(_ansi "$_sbase01")"
      export shigh="$(_ansi "$_sbase1")"

      _iterm "h$xbase03"
      _iterm "g$xbase0"
      ;;
    *)
      export sbg="$(_ansi "$_sbase02")"
      export sm="$(_ansi "$_sbase02")"
      export stext="$(_ansi "$_sbase2")"
      export scomment="$(_ansi "$_sbase2")"
      export shigh="$(_ansi "$_sbase2")"
      ;;
  esac
}

function slight {
  export CUE_SCHEME="slight"
  case "${TERM_PROGRAM:-}" in
    iTerm.app)
      export sbg="$(_ansi "$_sbase3")"
      export sm="$(_ansi "$_sbase2")"
      export stext="$(_ansi "$_sbase00")"
      export scomment="$(_ansi "$_sbase1")"
      export shigh="$(_ansi "$_sbase01")"

      _iterm "h$xbase3"
      _iterm "g$xbase00"
      ;;
    *)
      export sbg="$(_ansi "$_sbase2")"
      export sm="$(_ansi "$_sbase2")"
      export stext="$(_ansi "$_sbase02")"
      export scomment="$(_ansi "$_sbase02")"
      export shigh="$(_ansi "$_sbase02")"
      ;;
  esac
}

function snormal {
  case "${CUE_SCHEME:-sdark}" in
    sdark|slight)
      "$CUE_SCHEME"
      ;;
  esac
}

