#!/usr/bin/env bash

function _update_ps1_powerline() {
  PS1="$(powerline -error $? -mode flat -newline -priority root,cwd,user,host,ssh,perms,git-branch,jobs,exit,cwd-path,git-status -numeric-exit-codes -modules user,host,ssh,cwd,perms,gitlite,jobs,exit,root)"
}

PROMPT_COMMAND="_update_ps1_powerline; $PROMPT_COMMAND"
