#!/bin/bash

function aws_expiration {
  if [[ -z "${AWS_SESSION_EXPIRATION:-}" ]]; then
    return 0
  fi

  if ! type -P gdate >/dev/null; then
    return 0
  fi

  local time_left="$(( $(gdate -d "$AWS_SESSION_EXPIRATION" +%s) - $(date +%s) ))"

  echo -n "${AWS_DEFAULT_REGION:+${scomment}:${syellow}${AWS_DEFAULT_REGION}}"

  if [[ "$time_left" -lt 1 ]]; then
    echo -n "${scomment}:${sred}EXPIRED"
  elif [[ "$time_left" -lt 600 ]]; then
    echo -n "${scomment}:${sred}${time_left}"
  elif [[ "$time_left" -lt 1800 ]]; then
    echo -n "${scomment}:${sorange}${time_left}"
  else
    echo -n "${scomment}:${scyan}${time_left}"
  fi
}

function prompt_ssh {
  # ssh trail
  local hst_this
  if [[ -f $HOME/.name ]]; then
    hst_this=$(cat $HOME/.name)
  else
    hst_this=$(hostname -s)
  fi

  export CUE_HOST="$hst_this"

  local txt_origin
  if [[ -n ${LC_ORIGIN:-} && $LC_ORIGIN != "$hst_this" ]]; then
    txt_origin="/$LC_ORIGIN"
    export LC_ORIGIN="$hst_this${txt_origin}"
  fi

  local nm_user="$LOGNAME"

  if [[ "$nm_user" = "root" ]]; then
    nm_user="${sorange}${nm_user}"
  else
    nm_user="${shigh}${nm_user}"
  fi

  local nm_org="${AWS_VAULT:-${CONTEXT_ORG:-}}"
  echo -n" ${nm_user}${shigh}@$hst_this${nm_org:+${scomment}:${sorange}${nm_org}}$(aws_expiration)"
  if [[ -n ${LC_ORIGIN:-} && $LC_ORIGIN != "$hst_this" ]]; then
    echo "${scomment}${txt_origin}"
  fi
}
