#!/usr/bin/env bash

function filter_prompt {
  perl -pe 's{(\\\$)([^\$]+?)$}{ $1 $2}s'
}

function _update_ps1_powerline() {
  PS1="$(echo; powerline -error $? -colorize-hostname -newline -cwd-mode plain -priority root,cwd,user,host,ssh,perms,git-branch,jobs,exit,cwd-path,git-status -numeric-exit-codes -modules user,host,ssh,cwd,perms,git,jobs,exit | filter_prompt)"
}

PROMPT_COMMAND="_update_ps1_powerline"
