#!/usr/bin/env bash

PS1_START='${scomment}'
PS1_LEFT='${prn_git}${prn_pwd}'
PS1_RIGHT='${prn_ssh}'
PS1_END=' ${scomment} '
PS1_BREAK='${prn_error}${prn_jobs}${prn_root}${prn_shell}${prn_cli}'

function default_theme {
  PS1="$(eval echo "${PS1_START}${PS1_LEFT}")"
  if [[ -n "$prn_filler" ]]; then
    local prn_extra="${prn_filler} $(eval echo "${PS1_RIGHT}")$(eval echo "${PS1_END}")"
    PS1="${PS1}${prn_extra}"
  fi

  PS1="
${PS1}
$(eval echo "${PS1_START}${PS1_BREAK}") "

  PS2="${shigh} > "
}
