#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  mkdir -p "$shome/bin"

  local url_powerline_Darwin="https://github.com/justjanne/powerline-go/releases/download/v${POWERLINE_VERSION}/powerline-go-darwin-amd64"
  local url_powerline_Linux="https://github.com/justjanne/powerline-go/releases/download/v${POWERLINE_VERSION}/powerline-go-linux-amd64"

  local url_powerline="url_powerline_$(uname -s)"
  local fnm_powerline="$(basename "${!url_powerline}")-${POWERLINE_VERSION}"
  cache curl "$fnm_powerline" "${!url_powerline}"

  mkdir -p "$shome/bin"
  pushd "$shome/bin"
  cp "${DATA}/cache/curl/$fnm_powerline" "$shome/bin/powerline"
  chmod 755 "$shome/bin/powerline"
  ln -nfs powerline "$shome/bin/powerline-go"
  popd
}

main "$@"
