#!/usr/bin/env bash

function profile {
  local shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"
  PATH="$shome/bin:$shome/exec:$PATH"

  source "cue_solarized"
  source "cue_pwd"
  source "cue_ssh"
  source "cue_git"
  source "cue_theme"
  source "cue_prompt"
}

profile
